DROP USER project2 CASCADE;

CREATE USER project2
IDENTIFIED BY p4ssw0rd

DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;
GRANT CONNECT TO project2;
GRANT RESOURCE TO project2;
GRANT CREATE SESSION TO project2;
GRANT CREATE TABLE TO project2;
GRANT CREATE VIEW TO project2;
conn project2/p4ssw0rd;